# Generated by Django 5.0.2 on 2024-12-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeA', '0002_alter_crimereport_reporter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
