# Generated by Django 5.0.2 on 2024-12-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeA', '0003_crimereport_latitude_crimereport_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='evidence_photos/'),
        ),
    ]
